[[customizations.filesystem]]
mountpoint = "/"
minsize = "15 GiB"

# Optimize for development environment
[[customizations.filesystem]]
mountpoint = "/var"
minsize = "5 GiB"

[[customizations.filesystem]]
mountpoint = "/tmp"
minsize = "2 GiB"
